Sample statistics
========================================================

```{r echo=FALSE, fig.width=7, fig.height=7}
for(i in 1:nrow(summaryTable)) {
  sample = paste(summaryTable[i,]$sample, summaryTable[i,]$sample, sep="/")
  wd_sample = paste(workingDir, sample, sep="/")
  insert_size_metrics = paste(wd_sample,"_MERGED_sorted_dedup_MultipleMetrics.txt.insert_size_metrics", sep="")
  quality_by_cycle_metrics = paste(wd_sample,"_MERGED_sorted_dedup_MultipleMetrics.txt.quality_by_cycle_metrics", sep="")
  quality_distribution_metrics = paste(wd_sample,"_MERGED_sorted_dedup_MultipleMetrics.txt.quality_distribution_metrics", sep="")
  
  insert_size_metrics.table = read.table(file=insert_size_metrics, skip=10, head=TRUE)
  quality_by_cycle_metrics.table = read.table(file=quality_by_cycle_metrics, head=TRUE)
  quality_distribution_metrics.table = read.table(file=quality_distribution_metrics, head=TRUE)
  
  cat(paste("Sample =",summaryTable[i,]$sampleShort))
  
  print(plot_insert_size_metrics())
  print(plot_quality_by_cycle_metrics())
  print(plot_quality_distribution_metrics())
}
```

Hybrid selection specific metrics
========================================================
Bait interval file = `r unique(summaryTable$baitIntervals)`

Target interval file = `r unique(summaryTable$targetIntervals)`

```{r echo=FALSE, fig.width=11, fig.height=10}
plot_pctOffBait()
plot_meanTargetCov()
```

```{r echo=FALSE, fig.width=20, fig.height=10}
plot_pctTargetBases()
```

Hybrid selection specific metrics summary table
========================================================

```{r echo=FALSE, results='asis'}
print(xtable(summaryTableT[c(6:(nrow(summaryTableT)-3)),]),type='html')
```