Sample statistics
========================================================

```{r echo=FALSE, fig.width=7, fig.height=7}
for(i in 1:length(samples)) {
  samplePath = paste(samples[i],"QCStats",samples[i],sep="/")
  wd_sample = paste(workingDir, samplePath, sep="/")
  insert_size_metrics = paste(wd_sample,"_MultipleMetrics.txt.insert_size_metrics", sep="")
  quality_by_cycle_metrics = paste(wd_sample,"_MultipleMetrics.txt.quality_by_cycle_metrics", sep="")
  quality_distribution_metrics = paste(wd_sample,"_MultipleMetrics.txt.quality_distribution_metrics", sep="")
  
  insert_size_metrics.table = read.table(file=insert_size_metrics, skip=10, head=TRUE)
  quality_by_cycle_metrics.table = read.table(file=quality_by_cycle_metrics, head=TRUE)
  quality_distribution_metrics.table = read.table(file=quality_distribution_metrics, head=TRUE)
  
  cat(paste("Sample =",samples[i]))
  
  print(plot_insert_size_metrics())
  print(plot_quality_by_cycle_metrics())
  print(plot_quality_distribution_metrics())
}
```

Hybrid selection specific metrics
========================================================
```{r echo=FALSE}
if (hsMetrics){
  cat(paste("Bait interval file =", unique(summaryTable$baitIntervals)))
}
```
```{r echo=FALSE}
if (hsMetrics){
  cat(paste("Target interval file =", unique(summaryTable$targetIntervals)))
}
```

```{r echo=FALSE, fig.width=11, fig.height=10}
if (hsMetrics){
    plot_pctOffBait()
}
```   

```{r echo=FALSE, fig.width=11, fig.height=10}
if (hsMetrics){    
    plot_meanTargetCov()
}
```

```{r echo=FALSE, fig.width=20, fig.height=10}
if (hsMetrics){
    plot_pctTargetBases()
}
```

Hybrid selection specific metrics summary table
========================================================

```{r echo=FALSE, results='asis'}
if (hsMetrics){
  print(xtable(summaryTableT[c(6:(nrow(summaryTableT)-3)),]),type='html')
}
```